package(default_visibility = ["//visibility:public"])

licenses(["notice"])

cc_library(
    name = "assimp",
    srcs = ["libassimp.5.0.1.dylib"],
)

cc_library(
    name = "freetype",
    srcs = ["libfreetype.2.10.1.dylib"],
)

cc_library(
    name = "glfw",
    srcs = ["libglfw.3.3.2.dylib"],
)