package(default_visibility = ["//visibility:public"])

licenses(["notice"])

cc_library(
    name = "assimp",
    srcs = ["libassimp.4.1.0.dylib"],
)

cc_library(
    name = "freetype",
    srcs = ["libfreetype.6.dylib"],
)

cc_library(
    name = "glfw",
    srcs = ["libglfw.3.3.dylib"],
)